# Generated by Django 4.1.7 on 2023-06-16 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advertisement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0001_initial'),
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('approved', models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1)),
                ('production', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('advertisement_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.advertisement')),
                ('agency_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
                ('billboard_id', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='billboard.billboard')),
                ('media_agency_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='media_proposal', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
