# Generated by Django 4.1.7 on 2023-05-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_billboard_paid_alter_billboard_image'),
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proposal',
            name='billBoard_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='billboard.billboard'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
