# Generated by Django 4.1.7 on 2023-06-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='approved',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (2, 2)], default=1),
        ),
    ]
