# Generated by Django 4.1.7 on 2023-06-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_alter_billboard_image'),
        ('proposal', '0003_proposal_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='billboard_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='billboard.billboard'),
        ),
    ]
