# Generated by Django 4.1.7 on 2023-06-14 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_remove_agency_latitude_remove_agency_longitude'),
        ('proposal', '0004_alter_proposal_billboard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='agency_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency'),
        ),
    ]
