# Generated by Django 4.1.7 on 2023-06-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0005_proposal_agency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='production',
            field=models.BooleanField(default=False),
        ),
    ]
