# Generated by Django 4.1.7 on 2023-05-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_signature', models.ImageField(upload_to='')),
                ('agency_signature', models.ImageField(upload_to='')),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_total_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_free', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agency_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
                ('proposal_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='proposal.proposal')),
            ],
        ),
    ]
