# Generated by Django 4.1.7 on 2023-05-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_agency', '0001_initial'),
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='gross_total_tax',
            new_name='gross_total_fee',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='agency_id',
        ),
        migrations.AddField(
            model_name='contract',
            name='media_agency_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='media_agency.mediaagency'),
        ),
    ]
