# Generated by Django 4.1.7 on 2023-06-03 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agency_signature',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_signature',
            field=models.CharField(max_length=10000),
        ),
    ]
