# Generated by Django 4.1.7 on 2023-06-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contract_agency_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='customer_signature',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
