# Generated by Django 4.1.7 on 2023-06-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agency_signature',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customer_signature',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
