# Generated by Django 4.1.7 on 2023-06-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tx_ref',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
