# Generated by Django 4.1.7 on 2023-05-23 21:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0002_remove_agency_user_id_agency_channel_name_and_more'),
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(default=None, max_length=128)),
                ('agency_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
                ('billboard_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='billboard.billboard')),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
