# Generated by Django 4.1.7 on 2023-05-26 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_agency_user_id_agency_channel_name_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('billboard', '0006_billboard_monthly_rate_per_sq_alter_billboard_status'),
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='billboard_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='BillboardRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.rating')),
                ('billboard_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='billboard.billboard')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rating.rating',),
        ),
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('billboard_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rating.billboardrating')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyRating',
            fields=[
                ('rating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rating.rating')),
                ('agency_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('rating.rating',),
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('agency_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rating.agencyrating')),
            ],
        ),
    ]
