# Generated by Django 4.1.7 on 2023-05-26 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_agency_user_id_agency_channel_name_and_more'),
        ('billboard', '0006_billboard_monthly_rate_per_sq_alter_billboard_status'),
        ('rating', '0002_alter_rating_options_remove_rating_agency_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyrating',
            name='agency_id',
        ),
        migrations.RemoveField(
            model_name='agencyrating',
            name='rating_ptr',
        ),
        migrations.RemoveField(
            model_name='billboard',
            name='billboard_id',
        ),
        migrations.RemoveField(
            model_name='billboardrating',
            name='billboard_id',
        ),
        migrations.RemoveField(
            model_name='billboardrating',
            name='rating_ptr',
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={},
        ),
        migrations.RemoveField(
            model_name='rating',
            name='polymorphic_ctype',
        ),
        migrations.AddField(
            model_name='rating',
            name='agency_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='agency.agency'),
        ),
        migrations.AddField(
            model_name='rating',
            name='billboard_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='billboard.billboard'),
        ),
        migrations.AddField(
            model_name='rating',
            name='entity_type',
            field=models.CharField(default=None, max_length=9),
        ),
        migrations.DeleteModel(
            name='Agency',
        ),
        migrations.DeleteModel(
            name='AgencyRating',
        ),
        migrations.DeleteModel(
            name='Billboard',
        ),
        migrations.DeleteModel(
            name='BillboardRating',
        ),
    ]
