# Generated by Django 4.1.7 on 2023-05-26 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_alter_rating_entity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='entity_type',
        ),
    ]
