# Generated by Django 4.1.7 on 2023-05-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_remove_rating_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='entity_type',
            field=models.CharField(choices=[('Billboard', 'Billboard'), ('Agency', 'Agency')], default='Billboard', max_length=9),
        ),
    ]
