# Generated by Django 4.1.7 on 2023-05-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_alter_billboard_image'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='media_agency_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='task_metrics',
        ),
        migrations.AddField(
            model_name='employee',
            name='billboard_id',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.CASCADE, to='billboard.billboard'),
        ),
    ]
