# Generated by Django 4.1.7 on 2023-06-16 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_name', models.CharField(max_length=50)),
                ('advertisement_type', models.CharField(max_length=50)),
                ('duration_in_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quantity', models.IntegerField(default=0.0)),
                ('advertisement_file', models.URLField(default=None, max_length=1000)),
                ('approved', models.BooleanField(default=False)),
                ('adult_content', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
