# Generated by Django 4.1.7 on 2023-03-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement_type', models.CharField(max_length=50)),
                ('billBoard_id_or_agency_name', models.CharField(max_length=50)),
                ('duration_in_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('width', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('height', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('quantity', models.IntegerField(default=0.0)),
                ('advertisement_file', models.FileField(blank=True, null=True, upload_to='')),
                ('total_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
