# Generated by Django 4.1.7 on 2023-06-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageChecker',
        ),
    ]
