# Generated by Django 4.1.7 on 2023-06-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_delete_imagechecker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_file',
            field=models.URLField(default=None, max_length=1000),
        ),
    ]
