# Generated by Django 4.1.7 on 2023-05-31 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_rename_billboard_id_or_agency_name_advertisement_advertisement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='advertisement_file',
            field=models.URLField(default=None),
        ),
    ]
