# Generated by Django 4.1.7 on 2023-06-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_alter_advertisement_advertisement_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='adult_content',
            field=models.BooleanField(default=False),
        ),
    ]
