# Generated by Django 4.1.7 on 2023-06-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_alter_billboard_image_alter_billboard_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='width',
            field=models.IntegerField(),
        ),
    ]
