# Generated by Django 4.1.7 on 2023-03-30 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_alter_billboard_landowner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
