# Generated by Django 4.1.7 on 2023-05-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_alter_billboard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='status',
            field=models.CharField(choices=[('F', 'Free'), ('O', 'Occupied')], default=None, max_length=1),
        ),
    ]
