# Generated by Django 4.1.7 on 2023-05-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_alter_billboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
