# Generated by Django 4.1.7 on 2023-06-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_alter_billboard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='file',
            field=models.URLField(default=False),
        ),
    ]
