# Generated by Django 4.1.7 on 2023-05-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_alter_billboard_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='paid',
            field=models.BooleanField(),
        ),
    ]
