# Generated by Django 4.1.7 on 2023-06-15 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0004_billboard_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='file',
            field=models.URLField(default=''),
        ),
    ]
