# Generated by Django 4.1.7 on 2023-04-24 19:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0004_alter_billboard_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='rate',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
