# Generated by Django 4.1.7 on 2023-04-24 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landowner', '0005_remove_landowner_user_id_landowner_user'),
        ('billboard', '0005_alter_billboard_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billboard',
            name='landowner_id',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='landowner.landowner'),
        ),
    ]
