# Generated by Django 4.1.7 on 2023-06-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_alter_billboard_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='adult_content',
            field=models.BooleanField(default=False),
        ),
    ]
