# Generated by Django 4.1.7 on 2023-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_alter_billboard_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='monthly_rate_per_sq',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='status',
            field=models.CharField(choices=[('Free', 'Free'), ('Occupied', 'Occupied')], default=None, max_length=8),
        ),
    ]
