# Generated by Django 4.1.7 on 2023-05-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0006_alter_billboard_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='image',
            field=models.URLField(),
        ),
    ]
