# Generated by Django 4.1.7 on 2023-05-23 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_billboard_paid_alter_billboard_image'),
        ('billboard', '0007_billboard_paid_alter_billboard_image'),
    ]

    operations = [
    ]
