# Generated by Django 4.1.7 on 2023-05-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0008_merge_20230523_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='status',
            field=models.CharField(choices=[('F', 'Free'), ('O', 'Occupied')], default='F', max_length=1),
        ),
    ]
