# Generated by Django 4.1.7 on 2023-06-10 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_userprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
