# Generated by Django 4.1.7 on 2023-03-29 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_is_admin_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
