# Generated by Django 4.1.7 on 2023-03-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_alter_proposal_customer_id'),
        ('billboard', '0002_alter_billboard_landowner_id'),
        ('user', '0009_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='landowners_id',
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='landownerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
        migrations.DeleteModel(
            name='EmployeeProfile',
        ),
        migrations.DeleteModel(
            name='LandownerProfile',
        ),
    ]
