# Generated by Django 4.1.7 on 2023-06-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('channel_name', models.CharField(default=None, max_length=50)),
                ('media_agency_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='media_agency.mediaagency')),
            ],
        ),
    ]
