# Generated by Django 4.1.7 on 2023-06-16 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peak_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('normal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('production', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.URLField(max_length=1000)),
                ('channel_name', models.CharField(default=None, max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('media_agency_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
