# Generated by Django 4.1.7 on 2023-05-22 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_agency', '0001_initial'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='user_id',
        ),
        migrations.AddField(
            model_name='agency',
            name='channel_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='agency',
            name='media_agency_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='media_agency.mediaagency'),
        ),
    ]
