# Generated by Django 4.1.7 on 2023-06-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
