# Generated by Django 4.1.7 on 2023-06-14 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_agency_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
