# Generated by Django 4.1.7 on 2023-05-29 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_agency_user_id_agency_channel_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='with_out_production',
        ),
    ]
