# Generated by Django 4.1.7 on 2023-06-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_agency_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='longitude',
        ),
    ]
