# Generated by Django 4.1.7 on 2023-04-24 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landowner', '0003_remove_landowner_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landowner',
            name='user',
        ),
        migrations.AddField(
            model_name='landowner',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
