# Generated by Django 4.1.7 on 2023-04-24 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landowner', '0004_remove_landowner_user_landowner_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landowner',
            name='user_id',
        ),
        migrations.AddField(
            model_name='landowner',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
