# Generated by Django 4.1.7 on 2023-04-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landowner', '0005_remove_landowner_user_id_landowner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landowner',
            name='company_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
